name: Unzip and Build APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # اکسترکت فایل زیپ و جابه‌جایی تمامی محتویات به پوشه اصلی
    - name: Unzip Project
      run: |
        unzip -o *.zip -d temp_folder
        if [ -d "temp_folder/LifeTimeline_v0_1" ]; then
          cp -r temp_folder/LifeTimeline_v0_1/* .
        else
          cp -r temp_folder/* .
        fi
        rm -rf temp_folder

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # اعطای دسترسی اجرایی به gradlew
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # ساخت فایل APK
    - name: Build Debug APK
      run: ./gradlew assembleDebug

    # آپلود و ذخیره فایل APK خروجی
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: LifeTimeline-Debug-APK
        path: app/build/outputs/apk/debug/app-debug.apk
